-- Schema para o novo projeto Supabase.
-- Rode este script no SQL Editor do Supabase (novo projeto) antes de apontar
-- as env vars SUPABASE_URL / SUPABASE_SERVICE_KEY para ele.

create table if not exists public.pedidos (
    id               bigint generated by default as identity primary key,
    criado_em        timestamptz not null default now(),
    status           text,
    status_pagamento text,
    feito            boolean not null default false,

    nome             text,
    email            text,
    telefone         text,
    cpf              text,

    cep              text,
    rua              text,
    numero           text,
    complemento      text,
    bairro           text,
    cidade           text,
    estado           text,

    tipo_frete       text,
    prazo_frete      text,
    custo_frete      numeric,

    kit              text,
    nome_kit         text,
    quantidade       integer,
    tamanho          text,
    cor              text,

    forma_pagamento  text,
    subtotal         numeric,
    desconto         numeric,
    total            numeric,

    observacoes      text
);

create index if not exists pedidos_observacoes_idx on public.pedidos (observacoes);
create index if not exists pedidos_status_pagamento_idx on public.pedidos (status_pagamento);
create index if not exists pedidos_criado_em_idx on public.pedidos (criado_em desc);

create table if not exists public.bling_tokens (
    id            bigint primary key,
    access_token  text not null,
    refresh_token text not null,
    expires_at    timestamptz not null,
    updated_at    timestamptz not null default now()
);

-- O código acessa essas tabelas via REST (PostgREST) usando a Service Role
-- Key, que já bypassa RLS. Ainda assim, é recomendado habilitar RLS e não
-- expor essas tabelas com uma chave anon/public.
alter table public.pedidos enable row level security;
alter table public.bling_tokens enable row level security;
